apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Backstage
    email: mike.mochan@stanwell.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: infrastructure
  children: [team-smp]