apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/managed-by: kubernetes-component
    backstage.io/managed-by-location: url:https://github.com/mmochan/terraform-backstage/blob/main/kubernetes/component.yaml
spec:
  type: service
  lifecycle: experimental
  owner: my-team